{
    "dev":{
        "host":"aaa",
        "port":3306,
        "user":"aaa",
        "password":"aaa",
        "database":"aaa",
        "charset":"utf8"
        },
    "localhost":{
        "host":"localhost",
        "port":3306,
        "user":"root",
        "password":"root",
        "database":"ifs_test1",
        "charset":"utf8"
        },
    "sit":{
        "host":"ccc",
        "port":3306,
        "user":"ccc",
        "password":"ccc",
        "database":"ccc",
        "charset":"utf8"
        }
}
